name: Publish Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  ReleasePackage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Download
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: CreatePackage.yaml
          workflow_conclusion: success
          event: push
          name: xo-unity-spaces
          name_is_regexp: false
          path: package-temp

      - uses: spenserblack/actions-tag-to-release@v2.0.0

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: package-temp/xo-unity-spaces.unitypackage





